name: 'healthcare_dw'
version: '1.0.0'
config-version: 2

profile: 'healthcare_dw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  healthcare_dw:
    staging:
      +materialized: view
    dimensions:
      +materialized: table
    facts:
      +materialized: incremental
